version: '3.8'

services:
  lottery-bot:
    build: .
    container_name: lottery-bot
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_PATH=/app/data/lottery_bot.duckdb
      - WEB_HOST=0.0.0.0
      - WEB_PORT=5000
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./exports:/app/exports
      - ./logs:/app/logs
    env_file:
      - .env
    networks:
      - lottery-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: lottery-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - lottery-bot
    networks:
      - lottery-network

networks:
  lottery-network:
    driver: bridge

volumes:
  lottery-data:
    driver: local